### ISSUE TITLE
Generate and publish documentation

### ISSUE THREAD

**Issue by lenaorobei** [oco-research/openapi-spec#5]
Add to GitHub workflow:
- Generate docs and publish to the public Postman workspace (need to create one).

Docs: 
- https://learning.postman.com/docs/publishing-your-api/documenting-your-api/
- https://www.postman.com/api-documentation-tool/

**Comment by dshevtsov** [comment]
I want to try several options for the docs generators:
- [redoc](https://github.com/Redocly/redoc) ([Magento's reference](https://magento.redoc.ly/2.4.3-admin/tag/addresscleanse/) is built using a paid version of this tool)
- [RapiDoc](https://mrin9.github.io/RapiDoc/)
- postman

@lenaorobei, what do you think about using GitHub Pages for the docs?

**Comment by dshevtsov** [comment]
Documentation in Postman: https://documenter.getpostman.com/view/18675627/UVJigths

**Comment by lenaorobei** [comment]
@dshevtsov I havent seen such examples, but we definitely can try.

**Comment by dshevtsov** [comment]
We will use RapiDoc for this project

**Comment by dshevtsov** [comment]
It looks like there is a way to add samples from different programming languages. This is possible via adding the samples to the spec onto an additional field [x-code-samples](https://mrin9.github.io/RapiDoc/examples/code-samples.html#get-/code-samples).

**Comment by dshevtsov** [comment]
Created an orphan branch gh-pages that only contains documentation. Published with GitHub Pages.
https://oco-research.github.io/openapi-spec/

**Comment by dshevtsov** [comment]
Actually, I'm gonna use this GitHub issue for further customization of the documentation website

**Comment by dshevtsov** [comment]
Next steps to try:
- add the code examples from the generated SDKs
- add versioning

**Comment by dshevtsov** [comment]
Added templates in #14

**Comment by dshevtsov** [comment]
The existing automation successfully generated [1.1.1 php-sdk](https://github.com/oco-research/php-sdk/releases/tag/1.1.1) with the expected doc generator.
I enabled GitHub Pages for PHP sdk: https://oco-research.github.io/php-sdk/#overview
